/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.hvf.alephnull.fact.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum CheckPointLabel implements org.apache.thrift.TEnum {
  REMOTE_TX(0),
  SERVER_RX(1),
  AGENT_FORWARD(2),
  STREAM_QUEUED(3),
  FULLY_PROCESSED(4),
  COMMITTED_TO_FACTSTORE(5);

  private final int value;

  private CheckPointLabel(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static CheckPointLabel findByValue(int value) { 
    switch (value) {
      case 0:
        return REMOTE_TX;
      case 1:
        return SERVER_RX;
      case 2:
        return AGENT_FORWARD;
      case 3:
        return STREAM_QUEUED;
      case 4:
        return FULLY_PROCESSED;
      case 5:
        return COMMITTED_TO_FACTSTORE;
      default:
        return null;
    }
  }
}
